### ISSUE TITLE
Compilation in 32 bits

### ISSUE THREAD

**Issue by tathanhdinh** [BitFunnel/NativeJIT#58]
Hi everybody,
Many thanks for this new JIT library. I am trying to compile `NativeJIT` for `x86` arch but unfortunately it cannot compile. I have received some errors like:
 
    NativeJIT\inc\NativeJIT/BitOperations.h(99): error C3861: '_mm_popcnt_u64': identifier not found
    NativeJIT\inc\NativeJIT/BitOperations.h(111): error C3861: '_BitScanForward64': identifier not found
    ...

Is this normal? I cannot see any specific `ifdef` for `x86`, so is `NativeJIT` for `x64` only?

Many thanks.

**Comment by danluu** [comment]
Yes, it's x64 only. Additionally, it assumes some relatively recent instructions are available, like the popcnt instruction that you're seeing in the error.

I think that it wouldn't be very invasive if all you wanted to do was get a version that worked on a CPU without those specific instructions, but a non-x64 version would probably require a relatively large set of changes.

**Comment by danluu** [comment]
I'm going to close this, but feel free to re-open if you'd like to add 32-bit support and want some comments on what's necessary to do so. It would be great for us if we had 32-bit support, but it's a low priority for us because our use-case for this is in a search engine that we run on relatively modern hardware with hundreds of GBs of RAM so we're unlikely to add support ourselves. In terms of priority for us, `AVX` or `ARM` support would be more useful, but we'd be happy to provide guidance if this is important for you.
