### ISSUE TITLE
__lzcnt64 fix

### ISSUE THREAD

**Issue by rncar** [BitFunnel/NativeJIT#60]
`NativeJIT/inc/NativeJIT/BitOperations.h:137:35: error: use of undeclared identifier
      '__lzcnt64'
            *highestBitSetIndex = __lzcnt64(value);`

Fixed adding 
`#define __LZCNT__`
in BitOperations.h.

`[  PASSED  ] 108 tests`

 OSX Yosemite.

**Comment by danluu** [comment]
Thanks for the bug report and fix!

Also, could you please run the following command and paste the output back into this issue?

~~~
sysctl -n machdep.cpu.brand_string
~~~

I'd like to try to figure out if this issue is "because" of Yosemite or maybe because of a hardware difference.

**Comment by rncar** [comment]
Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz

**Comment by danluu** [comment]
Great! Thanks again!

I believe this is an Ivy Bridge CPU, which doesn't support `lzcnt`. Just for future reference for myself, I think that defining __LZCNT__ should still produce a correct result as long as we don't pass in `-mlzcnt` or something else that forces the compiler to think that the CPU supports `lzcnt`.

Again, just for future reference for myself, we have a test that calls `GetHighestBitSet` with a 0 operand. If that test passed, that seems to indicate that this fix doesn't cause the (potential) issue where older CPUs will interpret `lzcnt` as `bsr` (`bsr` is the same as `lzcnt`, except when the input operand is `0`) instead of throwing a `#ud`

**Comment by rncar** [comment]
If you need some more tests just tell me.

**Comment by danluu** [comment]
@mikucionisaau Hi! Did you try the fix suggested above, and if so, did tests still pass for you afterwards?

**Comment by mikucionisaau** [comment]
with `__LZCNT__` defined at the top of `BitOperations.h` I am getting something else:
```
In file included from /usr/lib/gcc/x86_64-linux-gnu/6/include/immintrin.h:73:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/x86intrin.h:48,
                 from /tmp/NativeJIT/inc/NativeJIT/BitOperations.h:37,
                 from /tmp/NativeJIT/inc/NativeJIT/CodeGen/X64CodeGenerator.h:32,
                 from /tmp/NativeJIT/inc/NativeJIT/CodeGen/FunctionBuffer.h:40,
                 from /tmp/NativeJIT/src/CodeGen/FunctionBuffer.cpp:26:
/usr/lib/gcc/x86_64-linux-gnu/6/include/lzcntintrin.h: In function ‘short unsigned int __lzcnt16(short unsigned int)’:
/usr/lib/gcc/x86_64-linux-gnu/6/include/lzcntintrin.h:41:29: error: ‘__builtin_clzs’ was not declared in this scope
   return __builtin_clzs (__X);
                             ^
src/CodeGen/CMakeFiles/CodeGen.dir/build.make:158: recipe for target 'src/CodeGen/CMakeFiles/CodeGen.dir/FunctionBuffer.cpp.o' failed

```
I am actually confused what this option is supposed to give.
I grepped the GCC headers for `__LZCNT__` and found only the following:
```
#ifndef __LZCNT__
#pragma GCC push_options
#pragma GCC target("lzcnt")
#define __DISABLE_LZCNT__
#endif /* __LZCNT__ */
```
And then it does not seem to be sensitive to `__DISABLE_LZCNT__` and it gets undefined at the end.

**Comment by mikucionisaau** [comment]
`clang-3.9` is also upset (even with `__LZCNT__` defined):
```
/tmp/NativeJIT/inc/NativeJIT/BitOperations.h:139:35: error: always_inline function '__lzcnt64'
      requires target feature 'lzcnt', but would be inlined into function 'GetHighestBitSet' that is compiled without support
      for 'lzcnt'
            *highestBitSetIndex = __lzcnt64(value);
```

Thus I replaced the `__lzcnt64(value)` call in `BitOperations.h` with the following binary search and then `make test` passes:
```
           *highestBitSetIndex = 64;
           if (value) {
               if (value & 0xFFFFFFFF00000000) { *highestBitSetIndex -=32; value >>= 32; }
               if (value & 0x00000000FFFF0000) { *highestBitSetIndex -=16; value >>= 16; }
               if (value & 0x000000000000FF00) { *highestBitSetIndex -= 8; value >>=  8; }
               if (value & 0x00000000000000F0) { *highestBitSetIndex -= 4; value >>=  4; }
               if (value & 0b0000000000001100) { *highestBitSetIndex -= 2; value >>=  2; }
               if (value & 0b0000000000000010) { *highestBitSetIndex -= 1; value >>=  1; }
               if (value) { *highestBitSetIndex -= 1; }
           }
```
Perhaps this could be surrounded with CPU checks to be more efficient on modern CPUs. Anyway, I don't know what I am doing :-)

**Comment by danluu** [comment]
Great! Thanks for the suggested workaround.

Yeah, I agree that we should have CPU checks that fall back to something that works on older CPUs and do something "fast" on modern CPUs. Unfortunately, I don't think that either @MikeHopcroft or I have easy access to a machine with an older CPU, so it's hard for us to check that we're doing something reasonable.

Let me dig around to see if I can find someone with an old atom or P4 or something, since I think we'll have all of our (x86) bases covered if we work on an atom and a P4 (although maybe we should also check an old AMD or Centaur chip or something).

That might take a while, though.

**Comment by nibroc** [comment]
I'm woefully under qualified to be weighing in on this, but it's piqued my interest watching it develop over the past few days, so I've been looking into it, and I think I might have a small bit to add.

In short, it looks like what is happening is that [GCC](https://github.com/gcc-mirror/gcc/blob/edd716b6b1caa1a5cb320a8cd7f626f30198e098/gcc/config/i386/lzcntintrin.h#L46) and [Clang](http://clang.llvm.org/doxygen/lzcntintrin_8h_source.html) both define `__lzcnt64` in a way such that they assume `lzcnt` will be supported (`target("lzcnt")`), or in other words, they both essentially implicitly assume `lzcnt` support unless unless `__LZCNT__` is defined (which seems a bit backwards, but... whatever). This means that somehow `__LZCNT__` needs to be defined on architectures where it's not supported.

Interestingly, this would make static binaries non portable since the static binary might use the non-existent lzcnt instruction if compiled on a Haswell and run on something older. Or, in other words, it would actually need to be a one time check at startup or something.

What I'm a bit confused on though, and I think I'm probably missing something here, is why even use lzcnt? The advantage of lzcnt over bsr is that lzcnt has more pleasant behavior if the argument is 0. `GetHighestBitSet` already has special logic for 0 though, so why not just use bsr? Or rather, why not just use `__builtin_clzll` (which is just `64 - bsr`)? gcc always provides it, and Clang appears to always provide it on x64 (and this can easily be checked on Clang with `__has_builtin(__builtin_clzll)` if there was a desire to fall back to a C version if necessary).

To make what has turned into a long post short, I think the following would work and be both performant and portable (at least across x64):

        // Stores the index of the highest 1 bit and returns true. Returns
            // false and leaves highestBitSetIndex in an underterminate state
            // if the value has no bits set.
            // Uses BSR instruction. See http://felixcloutier.com/x86/BSR.html
            inline
            bool GetHighestBitSet(uint64_t value, unsigned* highestBitSetIndex)
            {
    #ifdef _MSC_VER
            // VC++ provides _BitScanReverse64()
                return _BitScanReverse64(SameTargetSizeCast<BitScanType32>(highestBitSetIndex),
                                         value)
                       ? true
                       : false;
    #else
                if (value == 0) {
                    return false;
                }
                *highestBitSetIndex = 63 - static_cast<unsigned>(__builtin_clzll(value));
                return true;
    #endif
            }

Strictly speaking, this is not actually as efficient as raw bsr would be since the subtraction would be unnecessary with the real bsr instruction (which means bsr is actually more efficient than lzcnt here, now that I think about it), but it's equally efficient to the existing code.

**Comment by danluu** [comment]
Thanks for commenting. It's great that we're getting so much feedback!

> What I'm a bit confused on though, and I think I'm probably missing something here, is why even use lzcnt ... GetHighestBitSet already has special logic for 0 though

I think that we shouldn't use `GetHighestBitSet` and should just use `lzcnt` directly, which is issue #50 . But yes, given that we haven't fixed that (I believe that would require changing `ExpressionTree.h` and `CallNode.cpp`), it seems like we shouldn't use `lzcnt` here.

Before 684246d0, the code was doing basically what you suggest. I believe it was changed mostly because this seemed simpler and we (as in Bing) run entirely on newer hardware. It's probably worth changing back if we don't make the change suggested in #50 since it lets people run on older hardware without having to patch the code, but we're likely to eventually make the change in #50, which will put is back into the boat we're in right now.

**Comment by nibroc** [comment]
Ah, it appears I should have looked into more history around this. I didn't realize the code at one point actually had used __builtin_clz.

Is the desire for GetHighestBitSet to return the operand size (i.e. 64) if no bits are set, or what is the goal of #50? I'm afraid I'm probably missing something obvious. Is `lzcnt` innately faster than `bsr`? Or is the goal to avoid having to get out two pieces of data from GetHighestBit? Or is the goal to eliminate the extra conditional for the bsr 0 special case?

Is the end goal to turn this

        unsigned r = 0;
        while (BitOp::GetHighestBitSet(xmmVolatiles, &r))

into something more like this?

    unsigned r = BitOp::GetHighestBitSet(xmmVolatiles);
    while (r != std::numeric_limits<decltype(xmmVolatiles)>::digits) {
         // Do stuff to xmmVolatiles
        r = BitOp::GetHighestBitSet(xmmVolatiles);
    }

I hope I'm not causing a distraction or annoyance with what are probably stupid questions (please tell me if I am). I'm just intrigued by this since it seems like the code is currently using lzcnt + subtraction to essentially emulate bsr. I also have a bit of a vested interest in this since I'm wanting to use NativeJIT, but am currently weighing different work arounds since my machine doesn't support lzcnt :).

**Comment by danluu** [comment]
The minimal expectation of #50 is that `GetHighestBitSet` would return `64` and that every caller of `GetHighestBitSet` would, instead of checking the boolean result, would check for `== 64` or ` != 64`, which would eliminate the extra level of indirection we have now, where if the result is 0, we set a boolean, and then we may look at that boolean later.

> I hope I'm not causing a distraction or annoyance with what are probably stupid questions (please tell me if I am)

Not at all! I'm happy that people are interested in this project.

If you (or someone else) wants to submit a PR that replaces `lzcnt` with `__builtin_clzll`, that's fine and we would take that PR.

One day, we're going to hook up the open source version of BitFunnel to NativeJIT. If, when we do that, we find that the funny indirection described above makes a significant difference for BitFunnel's performance, then we'd try to figure out how to eliminate the extra indirection without causing problems for anyone with an older CPU who's relying on NativeJIT. If there's a PR that makes the change suggested in #50, keeps `lzcnt` here, and correctly falls back to other code on CPUs that don't support `lzcnt`, that would be even better.

If no one submits a PR, I think we'll eventually fix this, but we have some changes to BitFunnel that are higher priority for us at the moment, so it will take a while.

**Comment by nibroc** [comment]
The short version of this post is that I'm going to put together a pull request to use `__builtin_clzll` in a few minutes. As long as `-march=native` is set, and the machine has a Haswell processor, `__builtin_clzll` will use `lzcnt` under the hood.  Otherwise, it will fall back to `bsr`, so the desired behavior is actually already all there. 

Now that a clear path forward has been established, I don't think it's particularly necessary, but I'm still intrigued by all of this, so there's more thoughts below :).

-----

It's strange to me that lzcnt is though to be more efficient than bsr in this situation. After all, we're wanting to find the index of the highest bit set which is what bsr does. lzcnt requires arithmetic in the form of `63 - lzcnt` to get the index of the highest bit set. Also, both require special logic: bsr requires a check for zero, and lzcnt requires a check for `lzcnt(value) == 64` (since otherwise, we'd do `63 - lzcnt(64)` and get a -1, although... for efficiency's sake, that could be specified as the return value of GetHighestBitSet in the case no bits are set).

Unless lzcnt is way faster than bsr, I think the fastest loop possible is actually based on bsr and taking advantage that it sets the zero flag. I'm not sure it's possible to guarantee that will happen without inline assembly, but Clang actually appears to optimize the hell out of __builtin_clzll [when it's using bsr under the hood](https://godbolt.org/g/SzVJvQ):

```cpp
inline
bool GetHighestBitSet(unsigned long long value, unsigned* highestBitSetIndex)
{
  if (value == 0) {
    return false;
  }
  *highestBitSetIndex = 63 - static_cast<unsigned>(__builtin_clzll(value));
  return true;
}

int use(unsigned long long val) {
	unsigned bit;
  	while (GetHighestBitSet(val, &bit)) {
      val = val & ~(1 << bit);
  	}
  	return 0;
}
```

```asm
use(unsigned long long):                                # @use(unsigned long long)
        test    rdi, rdi
        je      .LBB0_2
.LBB0_1:                                # =>This Inner Loop Header: Depth=1
        bsr     rcx, rdi
        mov     eax, -2
        rol     eax, cl
        cdqe
        and     rdi, rax
        jne     .LBB0_1
.LBB0_2:
        xor     eax, eax
        ret
```

Note that the subtraction goes away. I also think with clever restructuring of the assembly, the initial je could maybe be eliminated by simply checking the zero flag after bsr (as is already being done).

Compared to [lzcnt](https://godbolt.org/g/gqK8K3) (using -1 as the sentinel, rather than 64 -- returning 64 is even worse):

```cpp
#include <x86intrin.h>
#include <limits>

inline
unsigned GetHighestBitSet(unsigned long long value)
{
  unsigned leading_zeros = __lzcnt64(value);
  return leading_zeros == 64 ? 64 : 63 - leading_zeros;
}

int use(unsigned long long val) {
	unsigned bit = GetHighestBitSet(val);
  	while (bit != std::numeric_limits<decltype(val)>::digits) {
      val = val & ~(1 << bit);
      bit = GetHighestBitSet(val);
  	}
  	return val;
}
```

```asm
use(unsigned long long):                                # @use(unsigned long long)
        jmp     .LBB0_2
.LBB0_1:                                #   in Loop: Header=BB0_2 Depth=1
        mov     eax, -2
        rol     eax, cl
        cdqe
        and     rdi, rax
.LBB0_2:                                # =>This Inner Loop Header: Depth=1
        lzcnt   rax, rdi
        mov     ecx, 63
        sub     ecx, eax
        cmp     ecx, -1
        jne     .LBB0_1
        xor     eax, eax
        ret
```

Note that the lzcnt version has to do an extra subtraction and an extra comparison, though the bsr version does have an extra test and je before entering the loop.

This is obviously an incredibly contrived example, and Clang is optimizing the loops quite cleverly in some places other than just jsr/lzcnt. For example, the bsr version checks if val is zero instead of trying to use the zero flag of bsr like I thought it would, but the lzcnt loop doesn't get a clever optimization like that -- it just does a subtract and compare. I do think it shows that bsr can be very, very efficient in this circumstance though.

Either way, it's probably not worth thinking about it all this much. My understanding of it is that these methods are only used to figure out register allocation when JITing code, so a few extra cycles is going to most likely be unnoticeable compared to if the generated code were less efficient. I just think the relation between BSR and LZCNT and BSR's weird

**Comment by danluu** [comment]
Thanks for all of the comments and help, everyone! 👍

**Comment by rncar** [comment]
Just to confirm, compiling fine now in a machine without native `lzcnt`. (Intel Xeon E5620).
All tests passed.

**Comment by pubcoder** [comment]
Works for me too (Intel Core i7-2600), thanks!

**Comment by windhw** [comment]
> 

bsr and lzcnt are totally different instructions. For a byte 0x01, lzcnt returns 7 while bst returns 1
